# Generated by Django 3.0.5 on 2020-05-18 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_created=datetime.datetime.now, auto_now=True)),
                ('step_action_model', models.BooleanField(default=False)),
                ('step_music_analysis', models.BooleanField(default=False)),
                ('step_planning_generation', models.BooleanField(default=False)),
                ('step_script_generation', models.BooleanField(default=False)),
                ('music_path', models.CharField(max_length=255)),
                ('pkl_path', models.CharField(max_length=255)),
                ('result_path', models.CharField(max_length=255)),
                ('score', models.SmallIntegerField(max_length=2)),
                ('status', models.SmallIntegerField(max_length=1)),
                ('execute_time', models.IntegerField(default=None, max_length=5)),
            ],
        ),
    ]
