# Generated by Django 3.0.6 on 2020-05-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan2dance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanage',
            name='execute_time',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='taskmanage',
            name='score',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='taskmanage',
            name='status',
            field=models.SmallIntegerField(),
        ),
    ]
