# Generated by Django 3.0.6 on 2020-05-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan2dance', '0002_auto_20200519_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanage',
            name='result_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taskmanage',
            name='score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='taskmanage',
            name='status',
            field=models.SmallIntegerField(null=True),
        ),
    ]
