# Generated by Django 3.0.6 on 2020-05-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan2dance', '0003_auto_20200519_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanage',
            name='execute_time',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
