# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new.ui',
# licensing of 'new.ui' applies.
#
# Created: Fri Feb  7 21:50:54 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Robot(object):
    def setupUi(self, Robot):
        Robot.setObjectName("Robot")
        Robot.resize(650, 772)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Robot.sizePolicy().hasHeightForWidth())
        Robot.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/myimages/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Robot.setWindowIcon(icon)
        Robot.setStyleSheet("\n"
                            "                #Robot{\n"
                            "                border:1px solid gray;\n"
                            "                border-radius:10px;\n"
                            "                padding:2px 4px;\n"
                            "                background-color: rgb(255, 255, 255);\n"
                            "        background-color: rgb(217, 214, 220);\n"
                            "                }\n"
                            "                QTextEdit{\n"
                            "                border:1px solid gray;\n"
                            "                border-radius:5px;\n"
                            "                padding:2px 4px;\n"
                            "                background-color: rgb(232, 232, 232);\n"
                            "                }\n"
                            "                                #tv_analysis{\n"
                            "                                border:1px solid gray;\n"
                            "                border-radius:5px;\n"
                            "                padding:2px 4px;\n"
                            "                background-color: rgb(232, 232, 232);\n"
                            "                                }\n"
                            "                QComboBox{\n"
                            "                border:1px solid gray;\n"
                            "                border-radius:2px;\n"
                            "                }\n"
                            "                QListWidget{\n"
                            "                border:1px solid gray;\n"
                            "                border-radius:6px;\n"
                            "                }\n"
                            "                #sawc_problem>QPushButton{\n"
                            "                border-style: dotted;\n"
                            "                border-width: 1px;\n"
                            "                border-color:gray;\n"
                            "                border-radius:4px;\n"
                            "                background-color: #09A3DC;\n"
                            "                color:#fff;\n"
                            "                }\n"
                            "                #sawc_problem>QPushButton:hover{\n"
                            "                background-color:rgb(60,195,245);\n"
                            "                }\n"
                            "                QWidget{\n"
                            "                border-radius:5px;\n"
                            "                }\n"
                            "                                QWidget#widget{\n"
                            "                                border:1px solid gray;\n"
                            "                                background-color: rgb(255, 255, 255);\n"
                            "                                }\n"
                            "                                QFrame#frame_model,QFrame#frame_analysis,QFrame#frame_planner,QFrame#frame_mtnx{\n"
                            "                                border:1px solid gray;\n"
                            "                                border-radius:5px;\n"
                            "                                }\n"
                            "                QLineEdit{\n"
                            "                border:1px solid gray;\n"
                            "                border-radius:10px;\n"
                            "                background-color:white;\n"
                            "                }\n"
                            "                                QListWidgetItem{\n"
                            "                                border-radius:5px;\n"
                            "                background-color: #09A3DC;\n"
                            "                color:#fff;\n"
                            "                                }\n"
                            "                QPushButton{\n"
                            "                border-radius:5px;\n"
                            "                background-color: #09A3DC;\n"
                            "                color:#fff;\n"
                            "                }\n"
                            "                QPushButton:hover{\n"
                            "                background-color:rgb(60,195,245);\n"
                            "                }\n"
                            "                #btn_connect{\n"
                            "                border-radius:5px;\n"
                            "                background-color: #4682B4;\n"
                            "                color:#000;\n"
                            "                }\n"
                            "                #btn_connect:hover{\n"
                            "                background-color:#B0C4DE;\n"
                            "                }\n"
                            "            ")
        self.scrollArea = QtWidgets.QScrollArea(Robot)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 631, 751))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -649, 614, 1400))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 1400))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollAreaWidgetContents.setAutoFillBackground(False)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 631, 1401))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.gridLayoutWidget)
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.frame_analysis = QtWidgets.QFrame(self.widget)
        self.frame_analysis.setGeometry(QtCore.QRect(10, 420, 601, 191))
        self.frame_analysis.setStyleSheet("border-color: rgb(102, 90, 90);")
        self.frame_analysis.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_analysis.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_analysis.setObjectName("frame_analysis")
        self.pb_analysis = QtWidgets.QProgressBar(self.frame_analysis)
        self.pb_analysis.setGeometry(QtCore.QRect(170, 10, 261, 21))
        self.pb_analysis.setProperty("value", 1)
        self.pb_analysis.setObjectName("pb_analysis")
        self.widget_2 = QtWidgets.QWidget(self.frame_analysis)
        self.widget_2.setGeometry(QtCore.QRect(20, 80, 141, 91))
        self.widget_2.setObjectName("widget_2")
        self.btn_segment_data = QtWidgets.QPushButton(self.widget_2)
        self.btn_segment_data.setGeometry(QtCore.QRect(10, 30, 121, 31))
        self.btn_segment_data.setObjectName("btn_segment_data")
        self.label_music_running = QtWidgets.QLabel(self.frame_analysis)
        self.label_music_running.setGeometry(QtCore.QRect(270, 10, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_music_running.setFont(font)
        self.label_music_running.setObjectName("label_music_running")
        self.label_4 = QtWidgets.QLabel(self.frame_analysis)
        self.label_4.setGeometry(QtCore.QRect(20, 40, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_analysis_output = QtWidgets.QLabel(self.frame_analysis)
        self.label_analysis_output.setGeometry(QtCore.QRect(190, 40, 391, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_analysis_output.setFont(font)
        self.label_analysis_output.setTextFormat(QtCore.Qt.AutoText)
        self.label_analysis_output.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_output.setObjectName("label_analysis_output")
        self.tv_analysis = QtWidgets.QTableView(self.frame_analysis)
        self.tv_analysis.setGeometry(QtCore.QRect(180, 60, 411, 121))
        self.tv_analysis.setObjectName("tv_analysis")
        self.wd_config_1 = QtWidgets.QWidget(self.widget)
        self.wd_config_1.setGeometry(QtCore.QRect(10, 50, 601, 71))
        self.wd_config_1.setAutoFillBackground(False)
        self.wd_config_1.setObjectName("wd_config_1")
        self.label = QtWidgets.QLabel(self.wd_config_1)
        self.label.setGeometry(QtCore.QRect(10, 10, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.cb_segment = QtWidgets.QComboBox(self.wd_config_1)
        self.cb_segment.setGeometry(QtCore.QRect(20, 40, 81, 22))
        self.cb_segment.setObjectName("cb_segment")
        self.cb_segment.addItem("")
        self.cb_segment.addItem("")
        self.label_2 = QtWidgets.QLabel(self.wd_config_1)
        self.label_2.setGeometry(QtCore.QRect(220, 10, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.wd_config_1)
        self.label_3.setGeometry(QtCore.QRect(480, 20, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.cb_past_music = QtWidgets.QComboBox(self.wd_config_1)
        self.cb_past_music.setGeometry(QtCore.QRect(470, 40, 91, 22))
        self.cb_past_music.setObjectName("cb_past_music")
        self.le_input_music = QtWidgets.QLineEdit(self.wd_config_1)
        self.le_input_music.setGeometry(QtCore.QRect(120, 40, 241, 21))
        self.le_input_music.setObjectName("le_input_music")
        self.btn_choose = QtWidgets.QPushButton(self.wd_config_1)
        self.btn_choose.setGeometry(QtCore.QRect(370, 40, 75, 23))
        self.btn_choose.setObjectName("btn_choose")
        self.btn_music_analysis = QtWidgets.QPushButton(self.widget)
        self.btn_music_analysis.setGeometry(QtCore.QRect(210, 380, 181, 31))
        self.btn_music_analysis.setAutoDefault(False)
        self.btn_music_analysis.setObjectName("btn_music_analysis")
        self.btn_run_planner = QtWidgets.QPushButton(self.widget)
        self.btn_run_planner.setGeometry(QtCore.QRect(190, 710, 231, 31))
        self.btn_run_planner.setAutoDefault(False)
        self.btn_run_planner.setObjectName("btn_run_planner")
        self.wd_config_2 = QtWidgets.QWidget(self.widget)
        self.wd_config_2.setGeometry(QtCore.QRect(10, 610, 601, 91))
        self.wd_config_2.setStyleSheet("")
        self.wd_config_2.setObjectName("wd_config_2")
        self.cb_best_rate = QtWidgets.QCheckBox(self.wd_config_2)
        self.cb_best_rate.setGeometry(QtCore.QRect(10, 30, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.cb_best_rate.setFont(font)
        self.cb_best_rate.setObjectName("cb_best_rate")
        self.label_5 = QtWidgets.QLabel(self.wd_config_2)
        self.label_5.setGeometry(QtCore.QRect(70, 10, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.cb_dumpy_action = QtWidgets.QCheckBox(self.wd_config_2)
        self.cb_dumpy_action.setGeometry(QtCore.QRect(150, 30, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.cb_dumpy_action.setFont(font)
        self.cb_dumpy_action.setObjectName("cb_dumpy_action")
        self.label_6 = QtWidgets.QLabel(self.wd_config_2)
        self.label_6.setGeometry(QtCore.QRect(310, 10, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.cb_planning_function = QtWidgets.QComboBox(self.wd_config_2)
        self.cb_planning_function.setGeometry(QtCore.QRect(470, 10, 91, 22))
        self.cb_planning_function.setObjectName("cb_planning_function")
        self.cb_planning_function.addItem("")
        self.cb_planning_function.addItem("")
        self.cb_beat_tracker = QtWidgets.QCheckBox(self.wd_config_2)
        self.cb_beat_tracker.setGeometry(QtCore.QRect(10, 60, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.cb_beat_tracker.setFont(font)
        self.cb_beat_tracker.setObjectName("cb_beat_tracker")
        self.cb_action_coherent = QtWidgets.QCheckBox(self.wd_config_2)
        self.cb_action_coherent.setGeometry(QtCore.QRect(150, 60, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.cb_action_coherent.setFont(font)
        self.cb_action_coherent.setObjectName("cb_action_coherent")
        self.hs_time_restrict = QtWidgets.QSlider(self.wd_config_2)
        self.hs_time_restrict.setGeometry(QtCore.QRect(340, 50, 160, 22))
        self.hs_time_restrict.setOrientation(QtCore.Qt.Horizontal)
        self.hs_time_restrict.setObjectName("hs_time_restrict")
        self.sb_time_restrict = QtWidgets.QSpinBox(self.wd_config_2)
        self.sb_time_restrict.setGeometry(QtCore.QRect(520, 50, 42, 22))
        self.sb_time_restrict.setObjectName("sb_time_restrict")
        self.lb_time_restrict = QtWidgets.QLabel(self.wd_config_2)
        self.lb_time_restrict.setGeometry(QtCore.QRect(370, 70, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lb_time_restrict.setFont(font)
        self.lb_time_restrict.setObjectName("lb_time_restrict")
        self.frame_planner = QtWidgets.QFrame(self.widget)
        self.frame_planner.setGeometry(QtCore.QRect(10, 750, 601, 311))
        self.frame_planner.setStyleSheet("border-color: rgb(102, 90, 90);")
        self.frame_planner.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_planner.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_planner.setObjectName("frame_planner")
        self.pb_planner = QtWidgets.QProgressBar(self.frame_planner)
        self.pb_planner.setGeometry(QtCore.QRect(170, 10, 261, 21))
        self.pb_planner.setProperty("value", 1)
        self.pb_planner.setObjectName("pb_planner")
        self.widget_3 = QtWidgets.QWidget(self.frame_planner)
        self.widget_3.setGeometry(QtCore.QRect(0, 60, 271, 221))
        self.widget_3.setObjectName("widget_3")
        self.lw_problem = QtWidgets.QListWidget(self.widget_3)
        self.lw_problem.setGeometry(QtCore.QRect(95, 20, 81, 191))
        self.lw_problem.setObjectName("lw_problem")
        self.label_problem_list = QtWidgets.QLabel(self.widget_3)
        self.label_problem_list.setGeometry(QtCore.QRect(100, 100, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_problem_list.setFont(font)
        self.label_problem_list.setStyleSheet("color: rgb(125, 116, 116);")
        self.label_problem_list.setObjectName("label_problem_list")
        self.lw_plan = QtWidgets.QListWidget(self.widget_3)
        self.lw_plan.setGeometry(QtCore.QRect(180, 20, 81, 191))
        self.lw_plan.setObjectName("lw_plan")
        self.label_plan_list = QtWidgets.QLabel(self.widget_3)
        self.label_plan_list.setGeometry(QtCore.QRect(200, 100, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_plan_list.setFont(font)
        self.label_plan_list.setStyleSheet("color: rgb(125, 116, 116);")
        self.label_plan_list.setObjectName("label_plan_list")
        self.lw_domain = QtWidgets.QListWidget(self.widget_3)
        self.lw_domain.setGeometry(QtCore.QRect(10, 20, 81, 191))
        self.lw_domain.setObjectName("lw_domain")
        self.label_domain = QtWidgets.QLabel(self.widget_3)
        self.label_domain.setGeometry(QtCore.QRect(20, 100, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_domain.setFont(font)
        self.label_domain.setStyleSheet("color: rgb(125, 116, 116);")
        self.label_domain.setObjectName("label_domain")
        self.label_planner_running = QtWidgets.QLabel(self.frame_planner)
        self.label_planner_running.setGeometry(QtCore.QRect(260, 10, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_planner_running.setFont(font)
        self.label_planner_running.setObjectName("label_planner_running")
        self.label_8 = QtWidgets.QLabel(self.frame_planner)
        self.label_8.setGeometry(QtCore.QRect(70, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.te_planner = QtWidgets.QTextEdit(self.frame_planner)
        self.te_planner.setGeometry(QtCore.QRect(270, 60, 321, 241))
        self.te_planner.setObjectName("te_planner")
        self.label_planner_output = QtWidgets.QLabel(self.frame_planner)
        self.label_planner_output.setGeometry(QtCore.QRect(280, 40, 301, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_planner_output.setFont(font)
        self.label_planner_output.setAlignment(QtCore.Qt.AlignCenter)
        self.label_planner_output.setObjectName("label_planner_output")
        self.label_images = QtWidgets.QLabel(self.widget)
        self.label_images.setGeometry(QtCore.QRect(240, 0, 121, 40))
        self.label_images.setMaximumSize(QtCore.QSize(140, 40))
        self.label_images.setText("")
        self.label_images.setPixmap(QtGui.QPixmap(":/myimages/logo.png"))
        self.label_images.setScaledContents(True)
        self.label_images.setObjectName("label_images")
        self.btn_action_model = QtWidgets.QPushButton(self.widget)
        self.btn_action_model.setGeometry(QtCore.QRect(190, 130, 231, 31))
        self.btn_action_model.setAutoDefault(False)
        self.btn_action_model.setObjectName("btn_action_model")
        self.frame_model = QtWidgets.QFrame(self.widget)
        self.frame_model.setGeometry(QtCore.QRect(10, 170, 601, 201))
        self.frame_model.setStyleSheet("border-color: rgb(102, 90, 90);")
        self.frame_model.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_model.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_model.setObjectName("frame_model")
        self.te_model = QtWidgets.QTextEdit(self.frame_model)
        self.te_model.setGeometry(QtCore.QRect(180, 70, 411, 121))
        self.te_model.setObjectName("te_model")
        self.pb_model = QtWidgets.QProgressBar(self.frame_model)
        self.pb_model.setGeometry(QtCore.QRect(170, 20, 261, 21))
        self.pb_model.setProperty("value", 1)
        self.pb_model.setObjectName("pb_model")
        self.label_model_running = QtWidgets.QLabel(self.frame_model)
        self.label_model_running.setGeometry(QtCore.QRect(270, 20, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_model_running.setFont(font)
        self.label_model_running.setObjectName("label_model_running")
        self.widget_4 = QtWidgets.QWidget(self.frame_model)
        self.widget_4.setGeometry(QtCore.QRect(20, 70, 151, 121))
        self.widget_4.setObjectName("widget_4")
        self.btn_dummy_action = QtWidgets.QPushButton(self.widget_4)
        self.btn_dummy_action.setGeometry(QtCore.QRect(10, 80, 121, 31))
        self.btn_dummy_action.setObjectName("btn_dummy_action")
        self.btn_base_action = QtWidgets.QPushButton(self.widget_4)
        self.btn_base_action.setGeometry(QtCore.QRect(10, 10, 111, 31))
        self.btn_base_action.setObjectName("btn_base_action")
        self.label_11 = QtWidgets.QLabel(self.frame_model)
        self.label_11.setGeometry(QtCore.QRect(20, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_model_output = QtWidgets.QLabel(self.frame_model)
        self.label_model_output.setGeometry(QtCore.QRect(190, 50, 391, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_model_output.setFont(font)
        self.label_model_output.setTextFormat(QtCore.Qt.AutoText)
        self.label_model_output.setAlignment(QtCore.Qt.AlignCenter)
        self.label_model_output.setObjectName("label_model_output")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(40, 120, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(40, 370, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(40, 700, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setGeometry(QtCore.QRect(50, 1070, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.btn_generate_mtnx = QtWidgets.QPushButton(self.widget)
        self.btn_generate_mtnx.setGeometry(QtCore.QRect(210, 1080, 201, 31))
        self.btn_generate_mtnx.setAutoDefault(False)
        self.btn_generate_mtnx.setObjectName("btn_generate_mtnx")
        self.frame_mtnx = QtWidgets.QFrame(self.widget)
        self.frame_mtnx.setGeometry(QtCore.QRect(10, 1120, 601, 191))
        self.frame_mtnx.setStyleSheet("border-color: rgb(102, 90, 90);")
        self.frame_mtnx.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_mtnx.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_mtnx.setObjectName("frame_mtnx")
        self.pb_mtnx = QtWidgets.QProgressBar(self.frame_mtnx)
        self.pb_mtnx.setGeometry(QtCore.QRect(170, 10, 261, 21))
        self.pb_mtnx.setProperty("value", 1)
        self.pb_mtnx.setObjectName("pb_mtnx")
        self.widget_5 = QtWidgets.QWidget(self.frame_mtnx)
        self.widget_5.setGeometry(QtCore.QRect(20, 80, 141, 91))
        self.widget_5.setObjectName("widget_5")
        self.btn_mtnx_data = QtWidgets.QPushButton(self.widget_5)
        self.btn_mtnx_data.setGeometry(QtCore.QRect(10, 30, 121, 31))
        self.btn_mtnx_data.setObjectName("btn_mtnx_data")
        self.label_mtnx_running = QtWidgets.QLabel(self.frame_mtnx)
        self.label_mtnx_running.setGeometry(QtCore.QRect(270, 10, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_mtnx_running.setFont(font)
        self.label_mtnx_running.setObjectName("label_mtnx_running")
        self.label_13 = QtWidgets.QLabel(self.frame_mtnx)
        self.label_13.setGeometry(QtCore.QRect(20, 40, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_mtnx_output = QtWidgets.QLabel(self.frame_mtnx)
        self.label_mtnx_output.setGeometry(QtCore.QRect(190, 40, 391, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_mtnx_output.setFont(font)
        self.label_mtnx_output.setTextFormat(QtCore.Qt.AutoText)
        self.label_mtnx_output.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mtnx_output.setObjectName("label_mtnx_output")
        self.te_mtnx = QtWidgets.QTextEdit(self.frame_mtnx)
        self.te_mtnx.setGeometry(QtCore.QRect(180, 60, 411, 121))
        self.te_mtnx.setObjectName("te_mtnx")
        self.btn_execute = QtWidgets.QPushButton(self.widget)
        self.btn_execute.setGeometry(QtCore.QRect(210, 1340, 191, 31))
        self.btn_execute.setObjectName("btn_execute")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Robot)
        QtCore.QMetaObject.connectSlotsByName(Robot)

    def retranslateUi(self, Robot):
        Robot.setWindowTitle(QtWidgets.QApplication.translate("Robot", "Plan2Dance", None, -1))
        self.btn_segment_data.setText(QtWidgets.QApplication.translate("Robot", "Segment Data", None, -1))
        self.label_music_running.setText(QtWidgets.QApplication.translate("Robot", "Running......", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Robot", "Input&&Output:", None, -1))
        self.label_analysis_output.setText(QtWidgets.QApplication.translate("Robot", "output", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Robot", "Segment Function:", None, -1))
        self.cb_segment.setItemText(0, QtWidgets.QApplication.translate("Robot", "Cluster", None, -1))
        self.cb_segment.setItemText(1, QtWidgets.QApplication.translate("Robot", "Slience", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Robot", "Input Music:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Robot", "Past Music:", None, -1))
        self.btn_choose.setText(QtWidgets.QApplication.translate("Robot", "Choose", None, -1))
        self.btn_music_analysis.setText(QtWidgets.QApplication.translate("Robot", "Music Analysis", None, -1))
        self.btn_run_planner.setText(QtWidgets.QApplication.translate("Robot", "Planning Problem Generation", None, -1))
        self.cb_best_rate.setText(QtWidgets.QApplication.translate("Robot", "BR", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Robot", "Preferences:", None, -1))
        self.cb_dumpy_action.setText(QtWidgets.QApplication.translate("Robot", "BI", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Robot", "Planning Function:", None, -1))
        self.cb_planning_function.setItemText(0, QtWidgets.QApplication.translate("Robot", "parallel", None, -1))
        self.cb_planning_function.setItemText(1, QtWidgets.QApplication.translate("Robot", "serial", None, -1))
        self.cb_beat_tracker.setText(QtWidgets.QApplication.translate("Robot", "SC", None, -1))
        self.cb_action_coherent.setText(QtWidgets.QApplication.translate("Robot", "CA", None, -1))
        self.lb_time_restrict.setText(QtWidgets.QApplication.translate("Robot", "Time Restrict (sec)", None, -1))
        self.label_problem_list.setText(QtWidgets.QApplication.translate("Robot", "Problem", None, -1))
        self.label_plan_list.setText(QtWidgets.QApplication.translate("Robot", "Plan", None, -1))
        self.label_domain.setText(QtWidgets.QApplication.translate("Robot", "Domain", None, -1))
        self.label_planner_running.setText(QtWidgets.QApplication.translate("Robot", "Running......", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Robot", "Input&&Output:", None, -1))
        self.label_planner_output.setText(QtWidgets.QApplication.translate("Robot", "output", None, -1))
        self.btn_action_model.setText(QtWidgets.QApplication.translate("Robot", "Action Model Generation", None, -1))
        self.label_model_running.setText(QtWidgets.QApplication.translate("Robot", "Running......", None, -1))
        self.btn_dummy_action.setText(QtWidgets.QApplication.translate("Robot", "Dummy Action", None, -1))
        self.btn_base_action.setText(QtWidgets.QApplication.translate("Robot", "Basic Actions", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Robot", "Input&&Output:", None, -1))
        self.label_model_output.setText(QtWidgets.QApplication.translate("Robot", "output", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Robot", "Step1:", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Robot", "Step2:", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Robot", "Step3:", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("Robot", "Step4:", None, -1))
        self.btn_generate_mtnx.setText(QtWidgets.QApplication.translate("Robot", "Robot Script Genration ", None, -1))
        self.btn_mtnx_data.setText(QtWidgets.QApplication.translate("Robot", "Robot Script", None, -1))
        self.label_mtnx_running.setText(QtWidgets.QApplication.translate("Robot", "Running......", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("Robot", "Input&&Output:", None, -1))
        self.label_mtnx_output.setText(QtWidgets.QApplication.translate("Robot", "output", None, -1))
        self.btn_execute.setText(QtWidgets.QApplication.translate("Robot", "Execute", None, -1))


from .images_rc import *
