y_state = ['forward', 'centre', 'backward']  # 向前， 中间， 向后
z_state = ['stand', 'half-squat', 'squat']  # 站立， 半蹲， 全蹲
hand_state = ["chest", 'others']  # 手部在胸前， 其他位置

NaoActionsDefine = {
    'abandon': {
        'hand_right_use': True,  # 执行过程用到右手
        'hand_left_use': True,  # 执行过程用到左手
        'leg_right_use': True,  # 执行过程用到右腿
        'leg_left_use': True,  # 执行过程用到左腿
        'start_space_y': y_state[1],  # 机器人身体倾斜状态
        'start_space_z': z_state[1],  # 机器人是否下蹲
        'start_hand_position': hand_state[0],  # 手的位置
        'end_space_y': y_state[1],  # 机器人身体倾斜状态
        'end_space_z': z_state[1],  # 机器人是否下蹲
        'end_hand_position': hand_state[0],  # 手的位置
        'time_change_allowed': True,  # 允许通过速率调整动作持续时间
        'coherent': []  # 后置固定动作组衔接
    },
    'akimbo': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': False,
        'leg_left_use': False,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': True,
        'coherent': ['akimboRaise']
    },
    'akimboDown': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': False,
        'leg_left_use': False,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': True,
        'coherent': ['akimboRaise']
    },
    'akimboRaise': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': False,
        'leg_left_use': False,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': True,
        'coherent': []
    },
    'allForMe': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[1],
        'start_space_z': z_state[1],
        'start_hand_position': hand_state[0],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[0],
        'time_change_allowed': True,
        'coherent': []
    },
    'armsUpward': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': False,
        'leg_left_use': False,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': True,
        'coherent': []
    },
    'beatUpAndDown': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': False,
        'leg_left_use': False,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[0],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[0],
        'time_change_allowed': True,
        'coherent': []
    },
    # 'crossFingers': {
    #     'hand_right_use': True,
    #     'hand_left_use': True,
    #     'leg_right_use': False,
    #     'leg_left_use': False,
    #     'start_space_y': y_state[1],
    #     'start_space_z': z_state[0],
    #     'start_hand_position': hand_state[1],
    #     'end_space_y': y_state[1],
    #     'end_space_z': z_state[0],
    #     'end_hand_position': hand_state[0],
    #     'time_change_allowed': False,
    #     'coherent': []
    # },
    'dancingYouth': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[0],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'drumRoll': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[0],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[0],
        'time_change_allowed': False,
        'coherent': []
    },
    'elbowTurn': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[2],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    # 'enlargeBosmHoodwink': {
    #     'hand_right_use': True,
    #     'hand_left_use': True,
    #     'leg_right_use': True,
    #     'leg_left_use': True,
    #     'start_space_y': y_state[2],
    #     'start_space_z': z_state[0],
    #     'start_hand_position': hand_state[1],
    #     'end_space_y': y_state[1],
    #     'end_space_z': z_state[1],
    #     'end_hand_position': hand_state[1],
    #     'time_change_allowed': False,
    #     'coherent': []
    # },
    'fastAdvance': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'finesseSwing': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': False,
        'leg_left_use': False,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': True,
        'coherent': []
    },
    'handAppearance': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[0],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[0],
        'time_change_allowed': False,
        'coherent': []
    },
    'handFly': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'handHeadFoot': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[0],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'handsBendInward': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[0],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'handsCircle': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[0],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[0],
        'time_change_allowed': False,
        'coherent': []
    },
    'HandsUpAndDown': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[0],
        'time_change_allowed': False,
        'coherent': []
    },
    'handsWaveDown': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': False,
        'leg_left_use': False,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': True,
        'coherent': []
    },
    'handsWaveUp': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': False,
        'leg_left_use': False,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': True,
        'coherent': []
    },
    'handUpAndDown': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[1],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'heavyPendulum': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[0],
        'end_space_y': y_state[0],
        'end_space_z': z_state[1],
        'end_hand_position': hand_state[0],
        'time_change_allowed': False,
        'coherent': []
    },
    'hitChest': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': False,
        'leg_left_use': False,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[0],
        'time_change_allowed': False,
        'coherent': []
    },
    # 'kettle': {
    #     'hand_right_use': True,
    #     'hand_left_use': True,
    #     'leg_right_use': True,
    #     'leg_left_use': True,
    #     'start_space_y': y_state[1],
    #     'start_space_z': z_state[0],
    #     'start_hand_position': hand_state[1],
    #     'end_space_y': y_state[1],
    #     'end_space_z': z_state[1],
    #     'end_hand_position': hand_state[1],
    #     'time_change_allowed': False,
    #     'coherent': []
    # },
    'leftAttack': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'leftFuels': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[0],
        'time_change_allowed': True,
        'coherent': []
    },
    'leftHandBend': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[1],
        'start_hand_position': hand_state[0],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[0],
        'time_change_allowed': False,
        'coherent': []
    },
    'leftHandsObliqueParallel': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': False,
        'leg_left_use': False,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[0],
        'time_change_allowed': False,
        'coherent': []
    },
    'leftHandWave': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': False,
        'leg_left_use': False,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': True,
        'coherent': []
    },
    'leftHook': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[1],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[0],
        'end_space_z': z_state[1],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'leftProtest': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[1],
        'start_hand_position': hand_state[0],
        'end_space_y': y_state[0],
        'end_space_z': z_state[1],
        'end_hand_position': hand_state[0],
        'time_change_allowed': True,
        'coherent': []
    },
    'leftPunch': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': False,
        'leg_left_use': False,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[0],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': True,
        'coherent': []
    },
    # 'leftRightOut': {
    #     'hand_right_use': True,
    #     'hand_left_use': True,
    #     'leg_right_use': True,
    #     'leg_left_use': True,
    #     'start_space_y': y_state[1],
    #     'start_space_z': z_state[0],
    #     'start_hand_position': hand_state[1],
    #     'end_space_y': y_state[0],
    #     'end_space_z': z_state[1],
    #     'end_hand_position': hand_state[1],
    #     'time_change_allowed': False,
    #     'coherent': []
    # },
    'leftRightRhythm': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': True,
        'coherent': ['handswavedown', 'leftRightWave']  # 表示本动作可衔接在哪些动作后面
    },
    'leftRightWave': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': ['leftRightRhythm']
    },
    'leftSideKick': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[0],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'LeftTurn': {
        'hand_right_use': False,
        'hand_left_use': False,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'liftingArm': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[0],
        'time_change_allowed': False,
        'coherent': ['LeftTurn']
    },
    'liftTheChest': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[0],
        'end_space_y': y_state[0],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[0],
        'time_change_allowed': False,
        'coherent': []
    },
    'mergeHand': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[1],
        'start_hand_position': hand_state[0],
        'end_space_y': y_state[0],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[0],
        'time_change_allowed': False,
        'coherent': ['liftTheChest']
    },
    'motionHands': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': False,
        'leg_left_use': False,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'openHeartLeft': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[2],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'parallelHands': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': True,
        'coherent': []
    },
    'parallelHandsAkimboErect': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': False,
        'leg_left_use': False,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': True,
        'coherent': []
    },
    'power': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': False,
        'leg_left_use': False,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[0],
        'end_space_y': y_state[0],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': ['raiseHandsTakeHear']
    },
    'putUpHandsdown': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[1],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'raiseHandAndDropDown': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[0],
        'end_space_z': z_state[1],
        'end_hand_position': hand_state[0],
        'time_change_allowed': False,
        'coherent': []
    },
    'raiseHandsTakeHear': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': False,
        'leg_left_use': False,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[0],
        'end_space_y': y_state[0],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[0],
        'time_change_allowed': False,
        'coherent': []
    },
    'rightBlock': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[1],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[0],
        'end_space_z': z_state[1],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'rightHandFan': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': False,
        'leg_left_use': False,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[0],
        'end_space_y': y_state[0],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[0],
        'time_change_allowed': True,
        'coherent': []
    },
    # 'rightHandUp': {
    #     'hand_right_use': True,
    #     'hand_left_use': True,
    #     'leg_right_use': True,
    #     'leg_left_use': True,
    #     'start_space_y': y_state[2],
    #     'start_space_z': z_state[1],
    #     'start_hand_position': hand_state[0],
    #     'end_space_y': y_state[1],
    #     'end_space_z': z_state[0],
    #     'end_hand_position': hand_state[0],
    #     'time_change_allowed': True,
    #     'coherent': []
    # },
    # 'rightHook': {
    #     'hand_right_use': True,
    #     'hand_left_use': True,
    #     'leg_right_use': True,
    #     'leg_left_use': True,
    #     'start_space_y': y_state[1],
    #     'start_space_z': z_state[0],
    #     'start_hand_position': hand_state[1],
    #     'end_space_y': y_state[1],
    #     'end_space_z': z_state[0],
    #     'end_hand_position': hand_state[1],
    #     'time_change_allowed': True,
    #     'coherent': []
    # },
    # 'rightLean': {
    #     'hand_right_use': True,
    #     'hand_left_use': True,
    #     'leg_right_use': True,
    #     'leg_left_use': True,
    #     'start_space_y': y_state[1],
    #     'start_space_z': z_state[1],
    #     'start_hand_position': hand_state[0],
    #     'end_space_y': y_state[2],
    #     'end_space_z': z_state[0],
    #     'end_hand_position': hand_state[0],
    #     'time_change_allowed': True,
    #     'coherent': []
    # },
    # 'rightSwing': {
    #     'hand_right_use': True,
    #     'hand_left_use': True,
    #     'leg_right_use': False,
    #     'leg_left_use': False,
    #     'start_space_y': y_state[2],
    #     'start_space_z': z_state[0],
    #     'start_hand_position': hand_state[0],
    #     'end_space_y': y_state[2],
    #     'end_space_z': z_state[1],
    #     'end_hand_position': hand_state[0],
    #     'time_change_allowed': False,
    #     'coherent': ['rightLean']
    # },
    'rightUppercut': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[0],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': ['roar']
    },
    # 'roar': {
    #     'hand_right_use': True,
    #     'hand_left_use': True,
    #     'leg_right_use': True,
    #     'leg_left_use': True,
    #     'start_space_y': y_state[1],
    #     'start_space_z': z_state[0],
    #     'start_hand_position': hand_state[1],
    #     'end_space_y': y_state[0],
    #     'end_space_z': z_state[1],
    #     'end_hand_position': hand_state[1],
    #     'time_change_allowed': False,
    #     'coherent': []
    # },
    # 'rotatingRightHand': {
    #     'hand_right_use': True,
    #     'hand_left_use': True,
    #     'leg_right_use': True,
    #     'leg_left_use': True,
    #     'start_space_y': y_state[2],
    #     'start_space_z': z_state[0],
    #     'start_hand_position': hand_state[1],
    #     'end_space_y': y_state[2],
    #     'end_space_z': z_state[0],
    #     'end_hand_position': hand_state[1],
    #     'time_change_allowed': False,
    #     'coherent': []
    # },
    'runaround': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[0],
        'end_space_z': z_state[1],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'runningMan': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[1],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[0],
        'end_space_z': z_state[1],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': ['runaround']
    },
    'soldierSalute': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'saluteSwingArm': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[0],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[0],
        'time_change_allowed': False,
        'coherent': []
    },
    'scratchingHead': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': False,
        'leg_left_use': False,
        'start_space_y': y_state[1],
        'start_space_z': z_state[1],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[2],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': True,
        'coherent': []
    },
    'shake': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[0],
        'end_space_y': y_state[0],
        'end_space_z': z_state[1],
        'end_hand_position': hand_state[0],
        'time_change_allowed': False,
        'coherent': []
    },
    'shakeElbow': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': False,
        'leg_left_use': False,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[0],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': True,
        'coherent': []
    },
    # 'shakeHands': {
    #     'hand_right_use': True,
    #     'hand_left_use': True,
    #     'leg_right_use': False,
    #     'leg_left_use': False,
    #     'start_space_y': y_state[1],
    #     'start_space_z': z_state[0],
    #     'start_hand_position': hand_state[1],
    #     'end_space_y': y_state[1],
    #     'end_space_z': z_state[0],
    #     'end_hand_position': hand_state[1],
    #     'time_change_allowed': True,
    #     'coherent': []
    # },
    'shockHands': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[0],
        'end_space_z': z_state[1],
        'end_hand_position': hand_state[0],
        'time_change_allowed': False,
        'coherent': ['shoulderRhythm']
    },
    'shockHandsToChest': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[1],
        'start_hand_position': hand_state[0],
        'end_space_y': y_state[0],
        'end_space_z': z_state[1],
        'end_hand_position': hand_state[0],
        'time_change_allowed': False,
        'coherent': []
    },
    'shoulderRhythm': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'sideMovement': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[0],
        'end_space_y': y_state[0],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'sidestepLeft': {
        'hand_right_use': False,
        'hand_left_use': False,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[1],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    # 'splitLeap': {
    #     'hand_right_use': True,
    #     'hand_left_use': True,
    #     'leg_right_use': True,
    #     'leg_left_use': True,
    #     'start_space_y': y_state[0],
    #     'start_space_z': z_state[1],
    #     'start_hand_position': hand_state[1],
    #     'end_space_y': y_state[1],
    #     'end_space_z': z_state[0],
    #     'end_hand_position': hand_state[1],
    #     'time_change_allowed': False,
    #     'coherent': []
    # },
    'spreadWings': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[2],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'squat': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[1],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[1],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'storingForce': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    # 'swingHandsFootSide': {
    #     'hand_right_use': True,
    #     'hand_left_use': True,
    #     'leg_right_use': True,
    #     'leg_left_use': True,
    #     'start_space_y': y_state[1],
    #     'start_space_z': z_state[0],
    #     'start_hand_position': hand_state[1],
    #     'end_space_y': y_state[1],
    #     'end_space_z': z_state[1],
    #     'end_hand_position': hand_state[1],
    #     'time_change_allowed': True,
    #     'coherent': []
    # },
    'swingHandsPutUp': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[0],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'swingShake': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[0],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': True,
        'coherent': []
    },
    'takeTheLeft': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[1],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[0],
        'time_change_allowed': False,
        'coherent': []
    },
    'twistWaist': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[0],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'upwardPunches': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[0],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'verticalArm': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[0],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'waveLeftAndRight': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[1],
        'end_space_y': y_state[0],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[1],
        'time_change_allowed': False,
        'coherent': []
    },
    'wildDance': {
        'hand_right_use': True,
        'hand_left_use': True,
        'leg_right_use': True,
        'leg_left_use': True,
        'start_space_y': y_state[0],
        'start_space_z': z_state[0],
        'start_hand_position': hand_state[0],
        'end_space_y': y_state[0],
        'end_space_z': z_state[0],
        'end_hand_position': hand_state[0],
        'time_change_allowed': False,
        'coherent': []
    },
}
